# Use postgres/example user/password credentials
version: '3.1'

services:
  admin:
    build:
      context: ..
      dockerfile: ./deploy/app.Dockerfile
    volumes:
      - media_volume:/usr/src/app/media/
      - static_volume:/usr/src/app/static/
    expose:
      - 8000
    env_file:
      - .env.example
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - .env.example
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume:
  static_volume: