# Generated by Django 4.1.3 on 2022-11-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ на печать', 'verbose_name_plural': 'Заказы на печать'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='order',
        ),
    ]
