# Generated by Django 4.1.3 on 2022-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_rename_user_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый заказ'),
        ),
    ]
