# Generated by Django 4.1.3 on 2022-11-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Просмотренно'),
        ),
    ]
